ltoppyl/mahjong-score-manage

- docs/api/api.yaml
- docs/api/unimplemented-api.yaml
- v1.0 で必要な API の仕様を OpenAPI を用いてドキュメント化した
- 既に実装済みの `/` における仕様を OpenAPI を用いてドキュメント化した
- close #10
- #10
> [BE] v1.0 で必要な API のドキュメントの作成

- frontend/components/atoms/PieChart/index.stories.tsx
- frontend/components/atoms/PieChart/index.tsx
- frontend/package.json
- frontend/yarn.lock
- ドーナツ型の円グラフコンポーネントの作成
確認手順
- ローカルでこのブランチに移動
- `yarn storybook` を実行 
- close #3
- #3
> [FE] ドーナツ型の円グラフコンポーネントの作成

- frontend/components/atoms/TileButton/index.stories.tsx
- frontend/components/atoms/TileButton/index.tsx
- frontend/package.json
- frontend/yarn.lock
- 麻雀牌型ボタンの作成
default
選択時、影を追加する
- close #8
- #8
> [FE] 麻雀牌型ボタンの作成

- frontend/components/atoms/RightAddonInput/index.stories.tsx
- frontend/components/atoms/RightAddonInput/index.tsx
- frontend/components/molecules/ScoreInput/index.stories.tsx
- frontend/components/molecules/ScoreInput/index.tsx
- 点数入力用コンポーネントの作成
- close #9
- #9
> [FE] 点数入力用コンポーネントの作成

- frontend/components/atoms/ResultCard/index.stories.tsx
- frontend/components/atoms/ResultCard/index.tsx
- frontend/components/atoms/Spacer/index.tsx
> [FE] 成績カードの作成

- frontend/components/organisms/Footer/index.stories.tsx
- frontend/components/organisms/Footer/index.tsx
- フッターコンポーネントの作成
- close #16
- #16
> [FE] フッターコンポーネントの作成

- frontend/components/atoms/TileButton/index.tsx
- frontend/components/templates/NotLogin/index.stories.tsx
- frontend/components/templates/NotLogin/index.tsx
- [FE] 非ログイン時のページコンポーネントの作成
- close #22
- #22
> [FE] 非ログイン時のページコンポーネントの作成

- frontend/components/atoms/RightAddonInput/index.stories.tsx
- frontend/components/atoms/RightAddonInput/index.tsx
- frontend/components/atoms/TileButton/index.stories.tsx
- frontend/components/atoms/TileButton/index.tsx
- frontend/components/molecules/ScoreInput/index.stories.tsx
- frontend/components/molecules/ScoreInput/index.tsx
- frontend/components/organisms/ScoreInputField/index.stories.tsx
- frontend/components/organisms/ScoreInputField/index.tsx
- frontend/components/templates/ResultInput/index.stories.tsx
- frontend/components/templates/ResultInput/index.tsx
- 入力欄コンポーネントの作成
ショット
- close #23
- #23
> [FE] 入力rann 

- frontend/.eslintrc.json
- frontend/components/molecules/ScoreInput/index.stories.tsx
- frontend/components/templates/NotLogin/index.stories.tsx
- frontend/components/templates/NotLogin/index.tsx
- frontend/firebase.ts
- frontend/hooks/useAuth.tsx
- frontend/package.json
- frontend/pages/_app.tsx
- frontend/stores/Recoil.tsx
- frontend/tsconfig.json
- frontend/yarn.lock
- ログイン・ログアウト機能の作成
- close #29
- #29
> [FE] ログイン・ログアウト機能の作成

- frontend/components/atoms/CustomModal/index.stories.tsx
- frontend/components/atoms/CustomModal/index.tsx
- frontend/components/atoms/LogoutButton/index.tsx
- カスタムモーダルの作成
- close #32
- #32
> [FE] カスタムモーダルの作成

- frontend/components/atoms/RightAddonInput/index.tsx
- frontend/components/atoms/TileButton/index.tsx
- frontend/components/organisms/Footer/index.tsx
- frontend/components/organisms/ScoreInputField/index.tsx
- frontend/components/templates/Result/index.tsx
- frontend/components/templates/ResultInput/index.tsx
- frontend/firebase.ts
- frontend/hooks/useAuth.tsx
- frontend/pages/_app.tsx
- frontend/pages/index.tsx
- frontend/pages/result.tsx
> [FE] ページの組み上げ

- backend/main.py
> [BE] ユーザが存在しない場合にのみ DB にデータを作成

- backend/main.py
- backend/utils/cal_point.py
- ポイントの計算機能の実装
- xxx
- close #42
- #42
> [BE] ポイントの計算機能の実装

- backend/.gitignore
- backend/Spacefile
- backend/main.py
- backend/requirements.txt
- DB のつなぎ先を本番環境と開発環境で分けるような設定を追加
- close #44
- #44
> DB のつなぎ先を本番環境と開発環境で分けるような設定を追加

- frontend/components/atoms/ResultCard/index.tsx
- frontend/components/organisms/Footer/index.tsx
- frontend/components/templates/Result/index.tsx
- frontend/components/templates/ResultInput/index.tsx
- レスポンシブに対応したスタイルの修正
- xxx
- close #36
- #36
> [FE] レスポンシブに対応したスタイルの修正

- frontend/api/postRecord.ts
- frontend/components/atoms/RightAddonInput/index.stories.tsx
- frontend/components/atoms/RightAddonInput/index.tsx
- frontend/components/atoms/TileButton/index.stories.tsx
- frontend/components/atoms/TileButton/index.tsx
- frontend/components/molecules/ScoreInput/index.stories.tsx
- frontend/components/molecules/ScoreInput/index.tsx
- frontend/components/organisms/ScoreInputField/index.stories.tsx
- frontend/components/organisms/ScoreInputField/index.tsx
- frontend/components/templates/NotLogin/index.tsx
- frontend/components/templates/ResultInput/index.stories.tsx
- 成績送信時のボタン周りの挙動の修正
- xxx
- close #41
- #41
> [FE] 成績送信時のボタン周りの挙動の修正

- frontend/components/atoms/TileButton/index.tsx
見た目の調節及び、storybookの使い方を理解する
- 牌型ボタンのサイズ変更
- xxx
-ボタンの視認性が損なわれていないか
- close #0
- #0
> style:牌型ボタンのサイズ変更

- frontend/components/templates/Result/index.tsx
- 成績のデータが無い場合の表示を追加した。
- xxx
- close #0
- #0
> feat: 成績データが無い場合の表示の追加

- backend/main.py
- DBの仕様を変更
-ネストを深くすることで、無駄な読み込みを減らす
- xxx
- close #53 
- #0
> feat: DBの仕様変更をした

- frontend/components/organisms/ScoreInputField/index.tsx
- frontend/components/templates/RecordInput/index.tsx
- 3麻と4麻をボタンで選択して切り替えられるようにした
- xxx
- ~~3麻でも4麻でも「データの送信に失敗しました」と表示されるが、どこに不具合があるのか分からない。~~ 送信出来ました
- コードが冗長な気がする
- stateの状態名や更新関数の命名に自信が無い（そもそもstateを使う必要があるのか分からない）
- Chakra UIのTabsコンポーネントを使えばもっと簡潔なコードになるかもしれない（但しFigmaと全く同じ見た目にするのは難しそう）
- close #77
- #0
> feat: 3麻と4麻を切り替えられるようにした

- .vscode/settings.json
- backend/main.py
- backend/requirements.txt
- backend/utils/timestamp.py
- frontend/api/fetchRecordList.tsx
- frontend/components/molecules/FilteringModal/index.stories.tsx
- frontend/components/molecules/FilteringModal/index.tsx
- frontend/components/organisms/ScoreInputField/index.tsx
- frontend/components/templates/RecordBoard/index.tsx
- frontend/package.json
- frontend/pages/records.tsx
- frontend/types/DataRange.ts
- frontend/utils/fetchTime.tsx
- frontend/yarn.lock
> [FE] 絞り込みの UI の作成
